# 9. gyakorlat
# NumPy II.

In [1]:
import numpy as np

## Speciális mátrixok
A numpy-ban van pár beépített speciális mátrix, mint a csupa $0$, csupa $1$, identitás mátrix, illetve diagonális mátrix.

In [2]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [3]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [4]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [5]:
a = np.array([1,2,3,4])
np.diag(a)

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

## Mátrixok konkatenációja
Két mátrixot valamelyik tengely mentén az `np.concatenate` függvény segítségével tudunk összecsatolni:

In [6]:
A = np.ones((3,3))
I = np.eye(3)
B = np.concatenate([A, I])
print(B)

C = np.concatenate([A, I], axis=1)
print(C)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 1. 1. 1. 0. 0.]
 [1. 1. 1. 0. 1. 0.]
 [1. 1. 1. 0. 0. 1.]]


## Mátrix inverze, determinánsa, sajátértéke:

In [7]:
A = np.array([[1,2,3],[4,5,6],[7,8,10]])
print(np.linalg.det(A))

-3.000000000000001


In [8]:
print(np.linalg.inv(A))

[[-0.66666667 -1.33333333  1.        ]
 [-0.66666667  3.66666667 -2.        ]
 [ 1.         -2.          1.        ]]


In [9]:
l, v = np.linalg.eig(A)
print(l)
print(v)

[16.70749332 -0.90574018  0.19824686]
[[-0.22351336 -0.86584578  0.27829649]
 [-0.50394563  0.0856512  -0.8318468 ]
 [-0.83431444  0.4929249   0.48018951]]


## Mátrixok átformázása
Az `A` mátrix "formáját" megkphatjuk az alábbi módon:

In [10]:
A = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(A.shape)

(4, 3)


In [11]:
B = A.reshape(6,2)
print(B)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]


## Véletlen számok és univerzális függvények

A NumPy-ban is van random modul véletlen számok generálására. Így néz ki pl. egy 0 és 100 közötti véletlen egész szám generálása: 

In [12]:
x = np.random.randint(100)

print(x)

68


Valós szám 0 és 1 között:

In [13]:
x = np.random.rand()

print(x)

0.8900380178303133


Véletlen elemű tömböket is generálhatunk:

1D tömb 5 db, 0 és 100 között egész számmal:

In [14]:
x = np.random.randint(100, size=(5))

print(x)

[42 22 41 91 64]


3x5-ös tömb:

In [15]:
x = np.random.randint(100, size=(3, 5))

print(x)

[[13 82 96 24 23]
 [67 82 20 60 97]
 [92 32 58 93 22]]


Valósnál hasonlóan:

In [16]:
x = np.random.rand(5)

print(x)

[0.78460989 0.41792886 0.74113214 0.61959322 0.51382568]


In [17]:
x = np.random.rand(3,5)

print(x)

[[0.97937684 0.35742619 0.96468531 0.61160123 0.16985022]
 [0.22060105 0.10530251 0.72383373 0.63110234 0.74803846]
 [0.26158823 0.37155398 0.49514529 0.15837167 0.09894517]]


Egyenletes eloszlásból is tudunk mintavételezni:

In [18]:
x = np.random.uniform(low = 0, high = 5, size = 10)
x

array([0.66834323, 0.09639534, 4.53832491, 3.91040773, 0.64140169,
       3.42996953, 0.91914744, 2.13883213, 2.16475879, 2.97614893])

A `choice` metódussal az általunk megadott tömbből fog véletlenszerűen egy elemet kiválasztani:

In [19]:
x = np.random.choice([3, 5, 7, 9])

print(x)

3


In [20]:
x = np.random.choice([3, 5, 7, 9], size=(3, 5))

print(x)

[[9 7 7 5 3]
 [9 5 7 9 5]
 [5 7 7 7 9]]


Előírhatjuk azt is, melyiket mekkora valószínűséggel válassza (ezen valószínűségek 0 és 1 közötti számok, az összegük 1 legyen):

In [21]:
x = np.random.choice([3, 5, 7, 9], p=[0.1, 0.3, 0.6, 0.0], size=(100))

print(x)

[5 7 5 5 3 7 3 7 3 7 7 3 5 7 5 7 5 7 7 7 7 7 7 7 5 5 7 5 7 7 5 5 7 3 7 7 5
 5 5 7 5 7 5 7 7 7 5 7 7 7 5 5 7 7 7 7 7 7 5 7 5 3 7 7 3 7 7 7 5 7 5 7 7 5
 3 3 7 5 7 7 5 5 3 5 7 7 7 7 7 5 3 7 5 7 7 7 3 5 7 7]


Szükség lehet a számok sorrendjének véletlenszerű megváltoztatásra is (pl. kártya összekeverésének szimulációja). A `shuffle` megváltoztatja magát a tömböt.

In [22]:
arr = np.array([1, 2, 3, 4, 5])

np.random.shuffle(arr)

print(arr)

[5 1 4 3 2]


A `permutation` visszaadja a kevert tömböt, de az eredetit változatlanul hagyja.

In [23]:
arr = np.array([1, 2, 3, 4, 5])

print(np.random.permutation(arr))

[2 3 5 4 1]


In [24]:
print(arr)

[1 2 3 4 5]


# Lineáris algebrai egyenletrendszerek megoldása

Pl. Megoldandó az \
$2x_1 + x_2 + x_3 = 4$\
$x_1 + 3 x_2 + 2x_3 = 6$\
$x_1 + 2 x_2 +2 x_3 = 5$\
lineáris egyenletrendszer. 

In [25]:
import numpy as np
A = np.array([[2, 1, 1],
              [1, 3, 2],
              [1, 2, 2]])

b = np.array([4,
              6,
              5])

x = np.linalg.solve(A,b)
x

array([1., 1., 1.])

In [26]:
abs(A @ x - b) < 10e-12

array([ True,  True,  True])

## Feladat:
Számítsd ki az $A$ mátrix inverzét lineáris egyenletrendszer(ek) megoldásával! Ellenőrizheted a számításaidat az `np.linalg.inv` függvénnyel.

Hogyan lehetne egyetlen egyenletrendszer megoldásával megkapni az inverzet?

## Feladat:
Legyen
$$
    \begin{equation}
        F =
        \begin{bmatrix}
            1 & 1 \\
            1 & 0
        \end{bmatrix},\,
        u_0 = 
        \begin{bmatrix}
            1 \\
            0
        \end{bmatrix}.
    \end{equation}
$$
Definiáljuk a következő sorozatot:
$$
\begin{equation}
    u_k = F^ku,\quad\forall k\geq 1.
\end{equation}
$$
Mi lesz az $u_k$ vektorok második koordinátáiból képzett sorozat?

## Feladat:
a) Legyen $x = \left(2,3,4,5,6\right)$ és $m=6$. Készítsd el a Vandermonde-mátrixát!
$$
\begin{equation}
    V^m_x =
    \begin{bmatrix}
        1 & x_1 & x_1^2 & \dots & x_1^m \\
        1 & x_2 & x_2^2 & \dots & x_2^m \\
        \vdots & \vdots & \ddots & \vdots \\
        1 & x_n & x_n^2 & \dots & x_n^m
    \end{bmatrix}
\end{equation}
$$

